---
title: "Bacteria Drying : Introduction"
subtitle: "NCSU ST 542 Consulting Project"
author: "Bruce Campbell"
latex_engine: xelatex
fontsize: 12pt
output: pdf_document
---

---
```{r setup, include=FALSE,echo=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(dev = 'pdf')
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(prompt=FALSE)
knitr::opts_chunk$set(fig.height=5)
knitr::opts_chunk$set(fig.width=7)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_knit$set(root.dir = ".")
library(latex2exp)   
library(pander)
library(ggplot2)
library(GGally)
setwd("C:/E/brucebcampbell-git/ncsu-consulting-project/")
```

## Bacteria Drying

Scientists study bacteria for a variety of reasons.  Bacteria have been the source of great human suffering and more recently it has become known that bacteria are also an important part of human health.  In addition to matters of human health and disease, scientists study bacteria as forms of alternative energy and bio-remediation.  The ability to store bacteria for long periods of time is an important research objective. Scientists need to be able to keep libraries of bacteria to compare bacterial populations over time and to share bacteria among colleagues.  For alternative energy purposes, if bacteria can reliably be dried and rehydrated then growth plants do not have to be collocated with productions plants.  This has the potential to effectively make bacteria a stored energy source.  For bio-remediation if bacteria can be reliably rehydrated on site then deployment becomes easier as storing and transproting the bacteria in a dehydrated state is more cost effective.   

This study aims to evaluate a variety of bacterial drying methodologies to determine optimal conditions for re-hydration.  The specific aim is to have mechanism capable of producing ethanol/acetate at rates higher than 20% of undried bacteria.  Variables used in the drying process include the addition of chemicals, different mechanisms for removal of oxygen, and different storage conditions.   Samples from the same bacterial population are exposed to different drying mechanisms, are rehydrated, and then measured for anaerobic respiration.  The population surviving the drying process is measured through the amount of carbon monoxide produced after rehydration.  Increasing numbers of bacteria that survive the drying process lead to decreasing carbon monoxide levels.  Since this measurement is the sum of many small contributions we expect the reponse to be normally distributed. The overall goals are to find the conditions which minimize the carbon monoxide levels - thus providing optimal conditions for bacteria rehydration. 

