---
title: "Bacteria Drying : Introduction"
subtitle: "NCSU ST 542 Consulting Project"
author: "Bruce Campbell"
latex_engine: xelatex
fontsize: 12pt
output: pdf_document
---

---
```{r setup, include=FALSE,echo=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(dev = 'pdf')
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(prompt=FALSE)
knitr::opts_chunk$set(fig.height=5)
knitr::opts_chunk$set(fig.width=7)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_knit$set(root.dir = ".")
library(latex2exp)   
library(pander)
library(ggplot2)
library(GGally)
```

## Bacteria Drying

Scientists study bacteria for a variety of reasons.  Bacteria have been the source of great human suffering and more recently it has become know that bacteria are also an important part of human health.  In addition to matters of human health and disease, scientists study bacteria as forms of alternative energy and bio-remediation.  The ability to store bacteria for long periods of time is an important research objective. Scientists need to be able to keep libraries of bacteria to compare bacterial populations and to share bacteria among colleagues.  For alternative energy purposes, if bacteria can reliably be dried and rehydrated then growth plants do not have to be collocated with productions plants.  This has the potential to effectively make bacteria a stored energy source.  For bio-remediation if bacteria can be reliably rehydrated on site then deployment becomes easier as storing and transporting the bacteria in a dehydrated state is more cost effective.   

This study aims to evaluate a variety of bacterial drying methodologies to determine optimal conditions for re-hydration.  The specific aim is to have mechanism capable of producing ethanol/acetate at rates higher than 20% of undried bacteria.  Variables used in the drying process include the addition of chemicals, different mechanisms for removal of oxygen, and different storage conditions.   Samples from the same bacterial population are exposed to different drying mechanisms, are rehydrated, and then measured for anaerobic respiration.  The population surviving the drying process is measured through the amount of carbon monoxide produced after rehydration.  Increasing numbers of bacteria that survive the drying process lead to decreasing carbon monoxide levels.  Since this measurement is the sum of many small contributions we expect the response to be normally distributed. The overall goals are to find the conditions which minimize the carbon monoxide levels - thus providing optimal conditions for bacteria rehydration. 


## Research 

### 1
Abstract
The dehydration of bacteria by vacuum exposure results in damage to the cell membrane. This membrane damage does not necessarily lead to cell death. A part of the dehydrated bacteria is capable of eliminating the membrane damage by repair processes. Repair can proceed rapidly under conditions that permit synthesizing activities. The kinetics of this repair process were studied by means of the membrane-mediated biosynthesis of the cell wall as well as by the recovery of resistance to small concentrations of lysozyme. Repair is a precondition for cell proliferation. At low temperature cells can conserve their membrane damage and the repair process can be initiated when conditions become favorable.

@article {PMID:12180476,
	Title = {Membrane damage in dehydrated bacteria and its repair},
	Author = {Frankenberg-Schwager, M and Turcu, G and Thomas, C and Wollenhaupt, H and Bucker, H},
	Volume = {13},
	Year = {1975},
	Journal = {Life sciences and space research},
	ISSN = {0075-9422},
	Pages = {83-88},
	URL = {http://europepmc.org/abstract/MED/12180476}
}

### 2 
Mechanisms of dehydration injury in bacteriaLes mécanismes des dommages par déshydratation???
Author links open overlay panelM.J.Ashwood-Smith???
Show more
https://doi.org/10.1016/0140-7007(80)90047-XGet rights and content
Résumé
Genetic injuries caused by freeze-drying and desiccation are discussed. The experiments clearly demonstrate that the process of freeze-drying causes a variety of mutations in bacteria. The number of mutations increases as a function of the duration of cold storage. Breaks in DNA single strands were produced and, immediately after freeze-drying, the activation and formation of lambda bacteriophages from lysogenic bacteria was observed. It is clear that cryopreservation is better than freeze-drying for the long term storage of microorganisms when one requires absolute genetic stability.



